In [67]:
import numpy as np
import string as s

In [ ]:
# generate a test dataframe


In [69]:
# help(string)
s.ascii_uppercase


'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [2]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [5]:
# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print(ridership[1, 3])
    print(ridership[1:3, 3:5])
    print(ridership[1, :])
    

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [8]:
# Vectorized operations on rows or columns
if True:
#     print(ridership[0, :] + ridership[1, :])
    print(ridership[:, 0] + ridership[:, 1])
    

[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [10]:
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print(a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [1]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = None # Replace this with your code
    mean_for_max = None # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [21]:
import pandas as pd

# Examples of vectorized operations on DataFrames:
# Change False to True for each block of code to see what it does

# Adding DataFrames with the column names
if True:
    df1 = pd.DataFrame({'a': [1, 2, 3, 5, 6, 4, 5], 'b': [4, 5, 6,4,4,4,4]})
    df2 = pd.DataFrame({'a': [10, 20, 30, 40, 50, 80, 100], 'b': [40, 50, 60,11,11,11,11]})
    print(df1 + df2)
    

     a   b
0   11  44
1   22  55
2   33  66
3   45  15
4   56  15
5   84  15
6  105  15


In [22]:
df3 = (df1 + df2)
df3

a   b
0   11  44
1   22  55
2   33  66
3   45  15
4   56  15
5   84  15
6  105  15

In [23]:
df3['d'] = df3.a.shift()

In [25]:
df3['e'] = df3.a - df3.d
df3


a   b     d     e
0   11  44   NaN   NaN
1   22  55  11.0  11.0
2   33  66  22.0  11.0
3   45  15  33.0  12.0
4   56  15  45.0  11.0
5   84  15  56.0  28.0
6  105  15  84.0  21.0

In [33]:
df3.index = ['k', 'l', 'm', 'n', 'o', 'p', 'q']
df3.columns = ['col1', 'col2', 'col3', 'col4']

In [42]:
df3.dtypes

col1      int64
col2      int64
col3    float64
col4    float64
dtype: object

In [39]:
new_index = ['k', 'l', 'p', 'm', 'n', 'o', 'q']
new_columns =  ['col3', 'col1', 'col2', 'col4']
df3.reindex(index=new_index, columns=new_columns)
# df3

col3  col1  col2  col4
k   NaN    11    44   NaN
l  11.0    22    55  11.0
p  56.0    84    15  28.0
m  22.0    33    66  11.0
n  33.0    45    15  12.0
o  45.0    56    15  11.0
q  84.0   105    15  21.0

In [58]:
def change_to_zero(df):
    return pd.Series([0]*df.shape[1])
#     return 0

In [52]:
for gr, df in df3.groupby('col4'):
    print(gr)
    print(df)

11.0
   col1  col2  col3  col4
l    22    55  11.0  11.0
m    33    66  22.0  11.0
o    56    15  45.0  11.0
12.0
   col1  col2  col3  col4
n    45    15  33.0  12.0
21.0
   col1  col2  col3  col4
q   105    15  84.0  21.0
28.0
   col1  col2  col3  col4
p    84    15  56.0  28.0


In [59]:

df3.groupby('col4').apply(change_to_zero)

0  1  2  3
col4            
11.0  0  0  0  0
12.0  0  0  0  0
21.0  0  0  0  0
28.0  0  0  0  0

In [28]:
def append_x(x):
    x = '_'.join([str(x), 'xxx'])
    return x
    

In [29]:
# use applymap to work on each element of a dataframe
df3.applymap(append_x)

a       b         d         e
0   11_xxx  44_xxx   nan_xxx   nan_xxx
1   22_xxx  55_xxx  11.0_xxx  11.0_xxx
2   33_xxx  66_xxx  22.0_xxx  11.0_xxx
3   45_xxx  15_xxx  33.0_xxx  12.0_xxx
4   56_xxx  15_xxx  45.0_xxx  11.0_xxx
5   84_xxx  15_xxx  56.0_xxx  28.0_xxx
6  105_xxx  15_xxx  84.0_xxx  21.0_xxx

In [ ]:
# Adding DataFrames with overlapping column names 
if False:
    df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
    df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
    print df1 + df2

# Adding DataFrames with overlapping row indexes
if False:
    df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
    df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
    print df1 + df2

# --- Quiz ---
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    return None

In [3]:
import time
for i in range(10):
    print(flush=Ture, i)
    time.sleep(1) 

SyntaxError: positional argument follows keyword argument (<ipython-input-3-1d9fafe9cd3f>, line 3)