In [4]:
import numpy as np
import pandas as pd
import math
from IPython.display import display, Math, Latex
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
wkdir = '/Users/stuartzong/pytorch_challenge/'
points = pd.read_csv(f'{wkdir}points.csv', header=None)
points.columns = ['x1', 'x2', 'y']
points.head(2)

x1        x2  y
0  0.78051 -0.063669  1
1  0.28774  0.291390  1

In [ ]:
points['x']

In [81]:
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [56]:
def prediction(X, W, b):

    return stepFunction((np.matmul(X,W)+b)[0])

In [95]:
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    num_wrongs = 0
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            num_wrongs+=1
            print(W, X[i], X[i]*learn_rate)
            W+=X[i]*learn_rate
#             W[0] += X[i][0]*learn_rate
#             W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            num_wrongs+=1
            print(W, X[i], X[i]*learn_rate)
            W-=X[i]*learn_rate
#             W[0] -= X[i][0]*learn_rate
#             W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    print('wrong pred:', num_wrongs)
    return W, b


In [88]:
a = np.array([2,3])
a
a+=7
a

array([ 9, 10])

In [12]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [96]:
X = np.array(points[['x1', 'x2']])
y = np.array(points['y'])
trainPerceptronAlgorithm(X, y)

[[0.70807258]
 [0.02058449]] [0.5533 1.    ] [0.005533 0.01    ]


ValueError: non-broadcastable output operand with shape (2,1) doesn't match the broadcast shape (2,2)

In [9]:
def softmax(L):
    denominator = np.array([math.exp(i) for i in L]).sum()
    percent = [i/denominator for i in L]
    return percent
    
    


In [10]:
softmax([3,2,1])

[0.09936119083879263, 0.06624079389252842, 0.03312039694626421]

In [99]:
# cross-entropy for two classes, e.g. gift or no-gift behind a door

display(Math(r'CE=-\sum_{i=1}^m y_{i}*ln(p_{i}) + (1-yi)*ln(1-pi)'))

<IPython.core.display.Math object>

In [86]:

P = [.8, .7, .1]
Y = [1,1,0]
# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    # log(x) without a base means the base is e
#     np data type understore is to differentiate from python data type
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))
cross_entropy(Y, P)

0.6851790109107685

In [97]:
# cross entropy for multi_classes, m is the classes eg. 3 animals behind a door, n is # of doors
display(Math(r'CE=-\sum_{i=1}^n \sum_{j=1}^m y_{ij}*ln(p_{ij})'))

<IPython.core.display.Math object>

In [81]:
Y = np.float_(Y)
P = np.float_(P)
Y * np.log(P)
(1 - Y) * np.log(1 - P)
np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))

array([-0.22314355, -0.35667494, -0.        ])

array([-0.        , -0.        , -0.10536052])

-0.6851790109107685

# Latex

In [6]:

display(Math(r'F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx'))
display(Math(r'c = \sqrt{a^2 + b^2}'))
display(Math(r'e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [85]:

np.float_(P)

TypeError: float() argument must be a string or a number, not 'list'

In [16]:
#sigmoid function: convert numbers to values between 0 and 1
# derivative of sigmoid function is sigmoid *(1 - sigmoid)
display(Math(r'\sigma=\frac{1}{1+e^{-x}}'))
display(Math(r'\sigma^/(x)=\sigma(x) * (1 - \sigma(x))'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [24]:
# error function: 
# suppose we have m points, 
display(Math(r'suppose\ we\ have\ m\ points,\ x^{(1)}, x^{(2)} ... x^{(m)}'))

<IPython.core.display.Math object>

In [17]:
And now, let's recall that if we have mm points labelled x^{(1)}, x^{(2)}, \ldots, x^{(m)},x 
(1)
 ,x 
(2)
 ,…,x 
(m)
 , the error formula is:

E = -\frac{1}{m} \sum_{i=1}^m \left( y_i \ln(\hat{y_i}) + (1-y_i) \ln (1-\hat{y_i}) \right)E=− 
m
1
​	 ∑ 
i=1
m
​	 (y 
i
​	 ln( 
y 
i
​	 
^
​	 )+(1−y 
i
​	 )ln(1− 
y 
i
​	 
^
​	 ))

SyntaxError: invalid syntax (<ipython-input-17-ef9005fed24b>, line 1)